obstacle_params:
# for LWX
  # - {x: 3.0, y: 0.0, z: 0.75, offset: 3.14, slower: 5.0, scale_x: 0.0, scale_y: 6.0, scale_z: 0.0}
  # - {x: 7.0, y: 0.0, z: 0.75, offset: -3.14, slower: 5.0, scale_x: 6.0, scale_y: 0.0, scale_z: 0.0}
  # - {x: 7.0, y: 0.0, z: 0.75, offset: 0.0, slower: 5.0, scale_x: 0.0, scale_y: 6.0, scale_z: 0.0}
  # - {x: 9.0, y: 0.0, z: 0.75, offset: -3.14, slower: 5.0, scale_x: 0.0, scale_y: 6.0, scale_z: 0.0}
  # - {x: 11.0, y: 0.0, z: 0.75, offset: 0.0, slower: 5.0, scale_x: 0.0, scale_y: 6.0, scale_z: 0.0}
  # - {x: 13.0, y: 0.0, z: 0.75, offset: -3.14, slower: 5.0, scale_x: 0.0, scale_y: 6.0, scale_z: 0.0}
  # - {x: 15.0, y: 0.0, z: 0.75, offset: 0.0, slower: 5.0, scale_x: 0.0, scale_y: 6.0, scale_z: 0.0}
  # - {x: 15.0, y: 0.0, z: 0.75, offset: 0.0, slower: 5.0, scale_x: 6.0, scale_y: 0.0, scale_z: 0.0}
  # - {x: 19.0, y: 0.0, z: 0.75, offset: 0.0, slower: 5.0, scale_x: 0.0, scale_y: 6.0, scale_z: 0.0}

# x/6: 9, 18, 27(1.5), 28.8(1.6), 30.6(1.7), 32.4(1.8), 36(2.0)
# y/5: 7.5, 15, 22.5

# ---------- scenario6: 10-1.5
# 24-0401
# - {x: 4.5, y: 3.0, z: 0.75, offset: 8.0, slower: 6.0, scale_x: 15.0, scale_y: 0.0, scale_z: 0.0}
# - {x: 7.0, y: -2.0, z: 0.75, offset: 5.3, slower: 6.0, scale_x: 18.0, scale_y: 0.0, scale_z: 0.0}
# - {x: 17.0, y: -2.0, z: 0.75, offset: 7.0, slower: 6.0, scale_x: 15.0, scale_y: 0.0, scale_z: 0.0}
# - {x: 13.0, y: 3.0, z: 0.75, offset: 7.2, slower: 6.0, scale_x: 18.0, scale_y: 0.0, scale_z: 0.0}

# - {x: 17.5, y: 1.6,  z: 0.75, offset: -2.0, slower: 6.0, scale_x: 18.0, scale_y: 15, scale_z: 0.0}
# - {x: 16.5, y: -1.6,   z: 0.75, offset: 4.5, slower: 6.0, scale_x: 18.0, scale_y: -15, scale_z: 0.0}
# - {x: 11.0, y: 1.6, z: 0.75, offset: 4.0, slower: 6.0, scale_x: 18.0, scale_y: 15, scale_z: 0.0}
# - {x: 12.0, y: -1.8,  z: 0.75, offset: 1.5, slower: 6.0, scale_x: 18.0, scale_y: -15, scale_z: 0.0}

# # - {x: 7.55, y: 1.0, z: 0.8, offset: 7.0, slower: 6.0, scale_x: 0.0, scale_y: 15.0, scale_z: 0.0}
# # - {x: 5.1, y: -0.485, z: 0.75, offset: 9.0, slower: 6.0, scale_x: 18, scale_y: 0.0, scale_z: 0.0}

# - {x: 7.5, y: 1.0, z: 0.8, offset: 6.0, slower: 6.0, scale_x: 0.0, scale_y: 15.0, scale_z: 0.0}
# - {x: 5.10, y: -0.485, z: 0.75, offset: 9.0, slower: 6.0, scale_x: 18, scale_y: 0.0, scale_z: 0.0}



# ---------- scenario5: 10-1.0
#24-0401
# - {x: 17.0, y: -2.4, z: 0.75, offset: 7.0, slower: 6.0, scale_x: 9.0, scale_y: 0.0, scale_z: 0.0}
# - {x: 13.0, y: 3.0, z: 0.75, offset: 10.0, slower: 12.0, scale_x: 18.0, scale_y: 0.0, scale_z: 0.0}
# - {x: 7.0, y: -2.4, z: 0.75, offset: 5.5, slower: 12.0, scale_x: 18.0, scale_y: 0.0, scale_z: 0.0}
# - {x: 1.0, y: 3.0, z: 0.75, offset: 8.0, slower: 6.0, scale_x: 9.0, scale_y: 0.0, scale_z: 0.0}

# - {x: 17.2, y: 1.6,  z: 0.75, offset: 3.5, slower: 8.5, scale_x: 9.0, scale_y: 7.5, scale_z: 0.0}
# - {x: 16.5, y: -1.8,   z: 0.75, offset: 8.5, slower: 8.5, scale_x: 9.0, scale_y: -7.5, scale_z: 0.0}
# - {x: 11.5, y: 1.6, z: 0.75, offset: 2.1, slower: 6.0, scale_x: 9.0, scale_y: 7.5, scale_z: 0.0}
# - {x: 12.0, y: -1.8,  z: 0.75, offset: 4.0, slower: 6.0, scale_x: 9.0, scale_y: -7.5, scale_z: 0.0}

# - {x: 7.55, y: 1.0, z: 0.8, offset: 6.0, slower: 6.0, scale_x: 0.0, scale_y: 15.0, scale_z: 0.0}
# # - {x: 5.1, y: -0.475, z: 0.75, offset: 9.0, slower: 6.0, scale_x: 18, scale_y: 0.0, scale_z: 0.0}
# - {x: 5.1, y: -0.480, z: 0.75, offset: 9.0, slower: 6.0, scale_x: 18, scale_y: 0.0, scale_z: 0.0}



# ---------- scenario4: 10-0.5
# 24-0329
# - {x: 17.0, y: -2.4, z: 0.75, offset: 8.0, slower: 6.0, scale_x: 6.0, scale_y: 0.0, scale_z: 0.0}
# - {x: 12.0, y: 2.4, z: 0.75, offset: -0.1, slower: 6.0, scale_x: 6.0, scale_y: 0.0, scale_z: 0.0}
# - {x: 7.0, y: -2.4, z: 0.75, offset: 0.1, slower: 6.0, scale_x: 6.0, scale_y: 0.0, scale_z: 0.0}
# - {x: 1.0, y: 2.4, z: 0.75, offset: 8.0, slower: 6.0, scale_x: 6.0, scale_y: 0.0, scale_z: 0.0}

# - {x: 17.5, y: 0.4,  z: 0.75, offset: 4.0, slower: 8.5, scale_x: 9.0, scale_y: 7.5, scale_z: 0.0}
# - {x: 16.5, y: -1.8,   z: 0.75, offset: 6.0, slower: 8.5, scale_x: 9.0, scale_y: -6.5, scale_z: 0.0}
# - {x: 13.0, y: 1.7, z: 0.75, offset: 2.0, slower: 8.5, scale_x: 9.0, scale_y: 7.5, scale_z: 0.0}
# - {x: 12.0, y: -1.8,  z: 0.75, offset: 6.0, slower: 8.5, scale_x: 9.0, scale_y: -7.5, scale_z: 0.0}

# - {x: 7.99, y: 1.35, z: 0.8, offset: 7.0, slower: 6.0, scale_x: 0.0, scale_y: 7.2, scale_z: 0.0}
# - {x: 5.0, y: -0.55, z: 0.75, offset: 9.0, slower: 6.0, scale_x: 12, scale_y: 0.0, scale_z: 0.0}

# ---------- scenario3: 5-1.5
# 24-0328
# - {x: 15.1, y: 0.5, z: 0.75, offset: 9.0, slower: 6.0, scale_x: 12, scale_y: 0.0, scale_z: 0.0}
# - {x: 14.40, y: 0.0, z: 0.8, offset: 1.5, slower: 4.0, scale_x: 0.0, scale_y: 15.0, scale_z: 0.0}
# - {x: 11.50, y: 0.5, z: 0.8, offset: 4.8, slower: 4.0, scale_x: 0.0, scale_y: 15.0, scale_z: 0.0}
# - {x: 7.70, y: 1.0, z: 0.8, offset: 6.0, slower: 6.0, scale_x: 0.0, scale_y: 15.0, scale_z: 0.0}
# - {x: 5.1, y: -0.47, z: 0.75, offset: 9.0, slower: 6.0, scale_x: 18, scale_y: 0.0, scale_z: 0.0}

# ---------- scenario2: 5-1.0
# 24-0327
# - {x: 5.1, y: -0.47, z: 0.75, offset: 9.0, slower: 6.0, scale_x: 18, scale_y: 0.0, scale_z: 0.0}
# - {x: 7.75, y: 1.0, z: 0.8, offset: 6.0, slower: 6.0, scale_x: 0.0, scale_y: 15.0, scale_z: 0.0}
# - {x: 11.20, y: 0.5, z: 0.8, offset: 2.0, slower: 6.0, scale_x: 0.0, scale_y: 15.0, scale_z: 0.0}
# - {x: 15.25, y: 0.0, z: 0.8, offset: 0.0, slower: 6.0, scale_x: 0.0, scale_y: 15.0, scale_z: 0.0}
# - {x: 15.1, y: 0.4, z: 0.75, offset: 9.0, slower: 6.0, scale_x: 18, scale_y: 0.0, scale_z: 0.0}

# ---------- scenario1: 5-0.5
# 24-0328
# - {x: 5.1, y: -0.5, z: 0.75, offset: 9.0, slower: 6.0, scale_x: 9.0, scale_y: 0.0, scale_z: 0.0}
# - {x: 6.5, y: 0.5, z: 0.75, offset: 5.5, slower: 6.0, scale_x: 0.0, scale_y: 7.5, scale_z: 0.0}
# - {x: 10.5, y: 0.5, z: 0.75, offset: 8.0, slower: 8.5, scale_x: 9.0, scale_y: 7.5, scale_z: 0.0}
# - {x: 13.5, y: -0.5, z: 0.75, offset: 1.0, slower: 8.5, scale_x: -9.0, scale_y: 7.5, scale_z: 0.0}
# - {x: 16.5, y: 0.5, z: 0.75, offset: 3.0, slower: 8.5, scale_x: 9.0, scale_y: 7.5, scale_z: 0.0}

# ------------------------------------------------------------------------------------------------------------------- gazebo
- {x: 5.1, y: -0.5, z: 1.0, offset: 9.0, slower: 6.0, scale_x: 9.0, scale_y: 0.0, scale_z: 0.0}
- {x: 6.5, y: 0.5, z: 1.0, offset: 5.5, slower: 6.0, scale_x: 0.0, scale_y: 7.5, scale_z: 0.0}
- {x: 10.5, y: 0.5, z: 1.0, offset: 8.0, slower: 8.5, scale_x: 9.0, scale_y: 7.5, scale_z: 0.0}
- {x: 13.5, y: -0.5, z: 1.0, offset: 1.0, slower: 8.5, scale_x: -9.0, scale_y: 7.5, scale_z: 0.0}
- {x: 16.5, y: 0.5, z: 20.0, offset: 3.0, slower: 8.5, scale_x: 9.0, scale_y: 7.5, scale_z: 0.0}