TARGET_VELOCITY: 1.0
PREDICT_TIME: 3.0
OBSTACLE_COST_GAIN: 2.0
TO_GOAL_COST_GAIN: 1.0
PATH_COST_GAIN: 0.4
ANGLE_RESOLUTION: 0.087
DT: 0.10
GOAL_THRESHOLD: 0.3
TURN_DIRECTION_THRESHOLD: 0.1
ANGLE_TO_GOAL_TH: pi
OBS_RANGE: 0.8
VELOCITY_SAMPLES: 5
YAWRATE_SAMPLES: 20
